name: api_client
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint_rules:
    git: https://github.com/altynbek132/lint_rules
  test: ^1.24.9

  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  retrofit_generator: ^8.1.1

flutter:
