// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTh8jyclH8JUkXpdDoiitE5Iv82XZHhwM',
    appId: '1:115711196774:web:09f609d0975893c8f7f7a7',
    messagingSenderId: '115711196774',
    projectId: 'autobir',
    authDomain: 'autobir.firebaseapp.com',
    storageBucket: 'autobir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tcYB5LYMM5bCXMC3mn-2yxL5lRvIctA',
    appId: '1:115711196774:android:d9c97c724b8d6fccf7f7a7',
    messagingSenderId: '115711196774',
    projectId: 'autobir',
    storageBucket: 'autobir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ead2AahRIdZ08YGvUaJ3c-zePCGsCcI',
    appId: '1:115711196774:ios:ce7f72c8db1cdb9af7f7a7',
    messagingSenderId: '115711196774',
    projectId: 'autobir',
    storageBucket: 'autobir.appspot.com',
    iosBundleId: 'kz.car-wash.autobir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ead2AahRIdZ08YGvUaJ3c-zePCGsCcI',
    appId: '1:115711196774:ios:312575d1a7ea3971f7f7a7',
    messagingSenderId: '115711196774',
    projectId: 'autobir',
    storageBucket: 'autobir.appspot.com',
    iosBundleId: 'com.example.autobir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTh8jyclH8JUkXpdDoiitE5Iv82XZHhwM',
    appId: '1:115711196774:web:43c1251ff471b26df7f7a7',
    messagingSenderId: '115711196774',
    projectId: 'autobir',
    authDomain: 'autobir.firebaseapp.com',
    storageBucket: 'autobir.appspot.com',
  );
}
